import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Script from 'next/script'
import Link from 'next/link'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>ColdCutCoder</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="keywords" content="next, blog, code blog, cold cut coder blog" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Script src="script.js"></Script>

      <nav className={styles.mainnav}>
        <ul>
          <Link href='/'><a><li>Home</li></a></Link>
          <Link href='/about'><a><li>About</li></a></Link>
          <Link href='/blog'><a><li>Blog</li></a></Link>
          <Link href='/contact'><a><li>Contact</li></a></Link>
        </ul>
      </nav>

      <main className={styles.main}>
        <h3 className={styles.title}>
          Cold Cut <a href="https://coder.com/">Coders</a>
        </h3>
      <Image className='myImg' src="/main.jpg" alt="image" width={736/2} height={490/2}/>
        <p className={styles.description}>
          A Blog for Inexperienced Coders like{' '}
          <code className={styles.code}>String = "Me"</code>
        </p>

        <div className="blogs">
          <h2>My Popular Blogs</h2>
          <div className="blogItem">
            <h3>How did it Start?</h3>
            <p>Birth was the first step</p>
          </div>
        <div className="blogItem">
          <h3>How did it Start?</h3>
          <p>Birth was the first step</p>
        </div>
        <div className="blogItem">
          <h3>How did it Start?</h3>
          <p>Birth was the first step</p>
        </div>
        <div className="blogItem">
          <h3>How did it Start?</h3>
          <p>Birth was the first step</p>
        </div>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
