import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Script from 'next/script'

export default function Home() {
  
  return (
    <div className={styles.container}>
      <style jsx>
        {`
          h2{
            font-size: 35px;
          }
          h3{
            font-size: 26px;
          }
        `}
      </style>
      <Head>
        <title>ColdCutCoder</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="keywords" content="next, blog, code blog, cold cut coder blog" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Script src="script.js"></Script>



      <main className={styles.main}>
        <h1 className={styles.title}>
          Cold Cut <a href="https://coder.com/">Coder</a> Blogs
        </h1>

        <div className={styles.imgWrap}>
          <Image className={styles.myImg} src="/main.jpg" alt="image" width={736 / 2} height={490 / 2} />
          </div>
          <p className={styles.description}>
            A Blog for Inexperienced Coders like{' '}
            <code className={styles.code}>String = "Me"</code>
          </p>
        

        <div className="blogs">
          <h2>My Popular Blogs</h2>
          <div className="blogItem">
            <h3>How did it Start?</h3>
            <p>Birth was the first step</p>
          </div>
          <div className="blogItem">
            <h3>How did it Start?</h3>
            <p>Birth was the first step</p>
          </div>
          <div className="blogItem">
            <h3>How did it Start?</h3>
            <p>Birth was the first step</p>
          </div>
        </div>
      </main>

      
    </div>
  )
}
